### ISSUE TITLE
Update CSS for type 3 lookups

### ISSUE THREAD

**Issue by RoelN** [Wakamai-Fondue/wakamai-fondue-engine#43]
Current CSS outputs CSS to only _turn on_ a feature, not to select specific lookups.

E.g. it will output `font-feature-settings: "aalt" 1;`, turning on the first set of alternates. But if there are multiple sets, the CSS should list them.

Something like:

```css
.bungee-aalt-set1 {
  font-feature-settings: "aalt" 1;
}

.bungee-aalt-set2 {
  font-feature-settings: "aalt" 2;
}
```
